name: Publish image

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  publish:

    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}

    steps:
    - uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: ./.github/actions/setvars
    - name: Docker login
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build images
      run: |
        docker build . --platform linux/amd64 --file Dockerfile --tag ${DOCKER_USER}/calc:$DATE_TAG
        docker build . --platform linux/amd64 --file Tests.Dockerfile --tag ${DOCKER_USER}/test:$DATE_TAG
    - name: Prepare net and app
      run: |
        docker network inspect test_net >/dev/null 2>&1 || docker network create test_net
        docker run --rm -d --name calc -e DJANGO_HOST=calc --network test_net ${DOCKER_USER}/calc:$DATE_TAG
    - name: Run tests
      run: |
        sleep 10
        docker run -t --network test_net --name test --rm ${DOCKER_USER}/test:$DATE_TAG /usr/local/bin/pytest -vs --port 8080 --host=calc
    - name: Docker push
      run: docker push ${DOCKER_USER}/calc:$DATE_TAG